---
swagger: "2.0"
info:
  version: "0.1"
  title: SDT Order
host: virtserver.swaggerhub.com
basePath: /Inmarsat/SDT-Order/0.1
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /productOrder:
    post:
      tags:
      - order
      summary: submit a product order
      description: ""
      operationId: createOrder
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - in: body
        name: order
        description: the order configuration
        required: true
        schema:
          $ref: '#/definitions/ProductOrder'
      responses:
        201:
          description: Created
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /productOrder/{id}:
    get:
      tags:
      - order
      summary: returns an order
      description: ""
      operationId: getOrder
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the order id
        required: true
        type: integer
      responses:
        200:
          description: Complete
          schema:
            $ref: '#/definitions/ProductOrder'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
    post:
      tags:
      - order
      summary: modifies an installed product
      description: ""
      operationId: modifySubscription
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the id of the order
        required: true
        type: integer
      - in: body
        name: order
        description: the order configuration
        required: true
        schema:
          $ref: '#/definitions/InstalledProducts'
      responses:
        200:
          description: Complete
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
    put:
      tags:
      - order
      summary: modifies a product order
      description: ""
      operationId: modifyOrder
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the id of the order
        required: true
        type: integer
      - in: body
        name: order
        description: the order configuration
        required: true
        schema:
          $ref: '#/definitions/ProductOrder'
      responses:
        200:
          description: Complete
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
    delete:
      tags:
      - order
      summary: cancels product order
      description: ""
      operationId: deleteOrder
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the id of the order
        required: true
        type: integer
      responses:
        200:
          description: Complete
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /productOrder/byCustomer/{id}:
    get:
      tags:
      - order
      summary: returns a list of product orders by customer id
      description: ""
      operationId: getOrderByCustomer
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the id of the customer
        required: true
        type: integer
      responses:
        200:
          description: Complete
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductOrder'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /productOrder/byName/{productName}:
    get:
      tags:
      - order
      summary: returns a list of product orders by product name
      description: ""
      operationId: getOrderByName
      produces:
      - application/json
      - application/xml
      parameters:
      - name: productName
        in: path
        description: the name of the product
        required: true
        type: string
      responses:
        200:
          description: Complete
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductOrder'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /productOrder/{id}/status:
    get:
      tags:
      - order
      summary: returns the status of a product order
      description: ""
      operationId: orderStatus
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the id of the order
        required: true
        type: integer
      responses:
        200:
          description: Complete
          schema:
            $ref: '#/definitions/ProductOrderStatus'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /productOrder/{id}/action:
    get:
      tags:
      - order
      summary: gets a list of possible actions on a product Order
      description: ""
      operationId: getProductOrderActions
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the product id
        required: true
        type: integer
      - name: actionName
        in: path
        description: the action to be taken
        required: true
        type: string
      responses:
        200:
          description: Complete
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /product/{id}:
    get:
      tags:
      - product
      summary: gets the product offering structure model
      description: ""
      operationId: getProduct
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the product id
        required: true
        type: integer
      responses:
        200:
          description: Complete
          schema:
            $ref: '#/definitions/Product'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /productOrder/orderConfiguration:
    post:
      tags:
      - order
      summary: submit a product order based on an order configuration
      description: ""
      operationId: createProductOrderConfiguration
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - in: body
        name: order
        description: the order configuration
        required: true
        schema:
          $ref: '#/definitions/ProductOrder'
      responses:
        201:
          description: Created
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /orderConfiguration:
    post:
      tags:
      - order
      summary: creates an order configuration
      description: ""
      operationId: createOrderConfiguration
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - in: body
        name: order
        description: the order configuration
        required: true
        schema:
          $ref: '#/definitions/ProductOrder'
      responses:
        201:
          description: Created
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /orderConfiguration/{id}:
    get:
      tags:
      - order
      summary: returns an order configuration
      description: ""
      operationId: getOrderConfiguration
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the order configuration id
        required: true
        type: integer
      responses:
        200:
          description: Complete
          schema:
            $ref: '#/definitions/ProductOrder'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
    put:
      tags:
      - order
      summary: modify a product order configuration
      description: ""
      operationId: modifyOrderConfiguration
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the id of the order
        required: true
        type: integer
      - in: body
        name: order
        description: the order configuration
        required: true
        schema:
          $ref: '#/definitions/ProductOrder'
      responses:
        200:
          description: Complete
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
    delete:
      tags:
      - order
      summary: deletes a product order configuration
      description: ""
      operationId: deleteOrderConfiguration
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the id of the order
        required: true
        type: integer
      responses:
        200:
          description: Complete
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /orderConfiguration/{id}/status:
    get:
      tags:
      - order
      summary: returns an order configuration status
      description: ""
      operationId: getOrderConfigurationStatus
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the product id
        required: true
        type: integer
      responses:
        200:
          description: Complete
          schema:
            $ref: '#/definitions/Status'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /orderConfiguration/{id}/action/{actionName}:
    post:
      tags:
      - order
      summary: performs an action on an order configuration
      description: ""
      operationId: orderConfigurationAction
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the product id
        required: true
        type: integer
      - name: actionName
        in: path
        description: the action to be taken on the rder configuration
        required: true
        type: string
      - in: body
        name: order
        description: the order configuration
        required: true
        schema:
          $ref: '#/definitions/ProductOrder'
      responses:
        201:
          description: Complete
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /orderConfiguration/{id}/template:
    post:
      tags:
      - order
      summary: creates an order configuration template
      description: ""
      operationId: createOrderConfigurationTemplate
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the product id
        required: true
        type: integer
      - in: body
        name: order
        description: the order configuration
        required: true
        schema:
          $ref: '#/definitions/ProductOrder'
      responses:
        201:
          description: Created
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /installedProduct/{id}:
    get:
      tags:
      - installedProduct
      summary: gets the installed product offering structure model
      description: ""
      operationId: getInstalledProduct
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the installedProduct id
        required: true
        type: integer
      responses:
        200:
          description: Complete
          schema:
            $ref: '#/definitions/InstalledProducts'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /installedProduct/{id}/query/{queryName}:
    get:
      tags:
      - installedProduct
      summary: returns an installedProduct using a given query
      description: ""
      operationId: getinstalledProductQuery
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the installedProduct id
        required: true
        type: integer
      - name: queryName
        in: path
        description: the field being queried on
        required: true
        type: string
      responses:
        200:
          description: Complete
          schema:
            $ref: '#/definitions/InstalledProducts'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /installedProduct/{id}/generateOrderConfiguration:
    get:
      tags:
      - installedProduct
      summary: generates an order configuration based on an installed product
      description: ""
      operationId: generateOrderConfiguration
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the installedProduct id
        required: true
        type: integer
      responses:
        200:
          description: Complete
          schema:
            $ref: '#/definitions/ProductOrder'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /device/{id}:
    get:
      tags:
      - device
      summary: returns the device infromation
      description: ""
      operationId: getDevice
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the id of the device
        required: true
        type: integer
      responses:
        200:
          description: Complete
          schema:
            $ref: '#/definitions/Device'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /device/{id}/status:
    get:
      tags:
      - device
      summary: returns the status of a device
      description: ""
      operationId: deviceStatus
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the id of the device
        required: true
        type: integer
      responses:
        200:
          description: Complete
          schema:
            $ref: '#/definitions/Status'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /device/{id}/action:
    get:
      tags:
      - device
      summary: gets a list of possible actions on the device
      description: ""
      operationId: deviceActions
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the device id
        required: true
        type: integer
      responses:
        200:
          description: Complete
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
    post:
      tags:
      - device
      summary: submits an action on a device
      description: ""
      operationId: createDeviceAction
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: the device id
        required: true
        type: integer
      - in: body
        name: action
        description: the device action
        required: true
        schema:
          $ref: '#/definitions/ActionItem'
      responses:
        200:
          description: Complete
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
definitions:
  ProductOrder:
    type: object
    required:
    - '@type'
    - billingAccountRef
    - orderItem
    - pricingScheduleRef
    - siteId
    properties:
      '@type':
        type: string
      priority:
        type: string
        enum:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
      contractId:
        type: string
      siteId:
        type: string
      externalOrderId:
        type: string
      externalProjectId:
        type: string
      pricingScheduleRef:
        type: string
      billingAccountRef:
        type: string
      orderItem:
        $ref: '#/definitions/OrderItem'
    example:
      billingAccountRef: billingAccountRef
      orderItem: ""
      '@type': '@type'
      externalProjectId: externalProjectId
      contractId: contractId
      siteId: siteId
      externalOrderId: externalOrderId
      priority: "0"
      pricingScheduleRef: pricingScheduleRef
  ProductOrderStatus:
    type: object
    required:
    - '@type'
    - orderItem
    properties:
      '@type':
        type: string
      orderItem:
        $ref: '#/definitions/OrderItem'
    example:
      orderItem: ""
      '@type': '@type'
  OrderItem:
    type: array
    items:
      $ref: '#/definitions/OrderItem_inner'
  Product:
    type: object
    required:
    - '@type'
    - id
    properties:
      id:
        type: string
      '@type':
        type: string
      product:
        $ref: '#/definitions/Product'
      characteristics:
        type: array
        items:
          $ref: '#/definitions/Characteristic'
    example:
      product: null
      characteristics:
      - name: name
        value: value
      - name: name
        value: value
      '@type': '@type'
      id: id
  InstalledProducts:
    type: object
    properties:
      '@type':
        type: string
      contractId:
        type: string
      siteId:
        type: string
      externalOrderId:
        type: string
      externalProjectId:
        type: string
      pricingScheduleRef:
        type: string
      billingAccountRef:
        type: string
      installedDate:
        type: string
        format: date
      status:
        $ref: '#/definitions/Status'
      subStatus:
        $ref: '#/definitions/Status'
      product:
        $ref: '#/definitions/InstalledProduct'
    example:
      billingAccountRef: billingAccountRef
      product: ""
      '@type': '@type'
      externalProjectId: externalProjectId
      installedDate: 2000-01-23
      contractId: contractId
      siteId: siteId
      externalOrderId: externalOrderId
      pricingScheduleRef: pricingScheduleRef
      subStatus:
        date: 2000-01-23
        name: name
        error:
          errorCode: errorCode
          description: description
      status:
        date: 2000-01-23
        name: name
        error:
          errorCode: errorCode
          description: description
  InstalledProduct:
    type: array
    items:
      $ref: '#/definitions/InstalledProduct_inner'
  Characteristic:
    type: object
    required:
    - name
    - value
    properties:
      name:
        type: string
      value:
        type: string
    example:
      name: name
      value: value
  Status:
    type: object
    required:
    - date
    - name
    properties:
      name:
        type: string
      date:
        type: string
        format: date
      error:
        $ref: '#/definitions/Error'
    example:
      date: 2000-01-23
      name: name
      error:
        errorCode: errorCode
        description: description
  ActionItem:
    type: object
    properties:
      device:
        $ref: '#/definitions/Device'
      action:
        type: string
      requestedStartDate:
        type: string
        format: date
      characteristics:
        type: array
        items:
          $ref: '#/definitions/Characteristic'
    example:
      characteristics:
      - name: name
        value: value
      - name: name
        value: value
      action: action
      device:
        characteristics:
        - name: name
          value: value
        - name: name
          value: value
        name: name
        id: id
      requestedStartDate: 2000-01-23
  Device:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      characteristics:
        type: array
        items:
          $ref: '#/definitions/Characteristic'
    example:
      characteristics:
      - name: name
        value: value
      - name: name
        value: value
      name: name
      id: id
  Error:
    type: object
    properties:
      errorCode:
        type: string
      description:
        type: string
    example:
      errorCode: errorCode
      description: description
  OrderItem_inner:
    required:
    - '@type'
    - action
    - product
    properties:
      '@type':
        type: string
      action:
        type: string
        enum:
        - add
        - modify
        - no_change
        - delete
      requestedStartDate:
        type: string
        format: date
      product:
        $ref: '#/definitions/Product'
      status:
        $ref: '#/definitions/Status'
      orderItem:
        $ref: '#/definitions/OrderItem'
  InstalledProduct_inner:
    properties:
      '@type':
        type: string
      id:
        type: string
      characteristics:
        type: array
        items:
          $ref: '#/definitions/Characteristic'
      product:
        $ref: '#/definitions/InstalledProducts'
x-apigee-id: SwaggerHubTest
